
const $RegisterThirstValueEvent = Java.loadClass("cn.mlus.thirst.foundation.common.event.RegisterThirstValueEvent")

NativeEvents.onEvent($RegisterThirstValueEvent, event => {
    const addDrink = (itemId, hydration, quenched) => {
        event.addDrink(Item.of(itemId).item, hydration, quenched)
    }

    const addFood = (itemId, hydration, quenched) => {
        event.addFood(Item.of(itemId).item, hydration, quenched)
    }

    const addContainer = itemId => {
        event.addContainer(Item.of(itemId).item)
    }

    // 饮品
    addDrink("minecraft:potion", 20, 20)
    addDrink("minecraft:honey_bottle", 5, 5)
    addDrink("thirst:terracotta_water_bowl", 20, 20)
    addDrink("create:builders_tea", 15, 15)
    addContainer("create:builders_tea")

    // 原版固体食物
    addFood("minecraft:apple", 2, 2)
    addFood("minecraft:golden_apple", 2, 2)
    addFood("minecraft:enchanted_golden_apple", 10, 10)
    addFood("minecraft:melon_slice", 8, 8)
    addFood("minecraft:carrot", 2, 2)
    addFood("minecraft:golden_carrot", 8, 8)
    addFood("minecraft:beetroot", 1, 1)
    addFood("minecraft:sweet_berries", 1, 1)
    addFood("minecraft:glow_berries", 1, 1)
    addFood("minecraft:chorus_fruit", 2, 2)
    addFood("minecraft:cod", 1, 1)
    addFood("minecraft:salmon", 1, 1)
    addFood("minecraft:tropical_fish", 1, 1)
    addFood("minecraft:beef", 2, 2)
    addFood("minecraft:porkchop", 2, 2)
    addFood("minecraft:mutton", 1, 1)
    addFood("minecraft:rabbit", 1, 1)
    addFood("minecraft:chicken", 1, 1)
    addFood("minecraft:cooked_cod", 3, 3)
    addFood("minecraft:cooked_salmon", 4, 4)
    addFood("minecraft:cooked_beef", 6, 6)
    addFood("minecraft:cooked_porkchop", 6, 6)
    addFood("minecraft:cooked_mutton", 4, 4)
    addFood("minecraft:cooked_rabbit", 3, 3)
    addFood("minecraft:cooked_chicken", 4, 4)
    addFood("minecraft:potato", 1, 1)

    // 原版汤类 / 炖菜
    addFood("minecraft:mushroom_stew", 6, 7)
    addFood("minecraft:beetroot_soup", 6, 7)
    addFood("minecraft:rabbit_stew", 10, 11)
    addFood("minecraft:suspicious_stew", 6, 7)

    // Farmers Delight 饮品
    addDrink("farmersdelight:milk_bottle", 8, 8)
    addDrink("farmersdelight:hot_cocoa", 7, 7)
    addDrink("farmersdelight:apple_cider", 8, 8)
    addDrink("farmersdelight:melon_juice", 10, 11)

    // // Farmers Delight 固体食物
    addFood("farmersdelight:tomato", 1, 1)
    addFood("farmersdelight:cabbage", 1, 1)
    addFood("farmersdelight:onion", 1, 1)
    addFood("farmersdelight:tomato_sauce", 2, 2)
    addFood("farmersdelight:fried_egg", 2, 2)
    addFood("farmersdelight:pumpkin_slice", 2, 1)
    addFood("farmersdelight:cabbage_leaf", 1, 0)
    addFood("farmersdelight:minced_beef", 1, 1)
    addFood("farmersdelight:beef_patty", 3, 3)
    addFood("farmersdelight:chicken_cuts", 1, 0)
    addFood("farmersdelight:cooked_chicken_cuts", 2, 2)
    addFood("farmersdelight:bacon", 1, 0)
    addFood("farmersdelight:cooked_bacon", 3, 3)
    addFood("farmersdelight:cod_slice", 1, 0)
    addFood("farmersdelight:cooked_cod_slice", 3, 2)
    addFood("farmersdelight:salmon_slice", 1, 0)
    addFood("farmersdelight:cooked_salmon_slice", 3, 3)
    addFood("farmersdelight:mutton_chops", 1, 1)
    addFood("farmersdelight:cooked_mutton_chops", 4, 3)
    addFood("farmersdelight:ham", 3, 2)
    addFood("farmersdelight:smoked_ham", 6, 5)
    addFood("farmersdelight:cake_slice", 3, 2)
    addFood("farmersdelight:apple_pie_slice", 3, 2)
    addFood("farmersdelight:sweet_berry_cheesecake_slice", 3, 2)
    addFood("farmersdelight:chocolate_pie_slice", 3, 2)
    addFood("farmersdelight:pumpkin_pie_slice", 2, 1)
    addFood("farmersdelight:fruit_salad", 4, 3)
    addFood("farmersdelight:sweet_berry_cookie", 1, 0)
    addFood("farmersdelight:honey_cookie", 1, 0)
    addFood("farmersdelight:melon_popsicle", 2, 1)
    addFood("farmersdelight:glow_berry_custard", 3, 2)
    addFood("farmersdelight:barbecue_stick", 6, 5)
    addFood("farmersdelight:egg_sandwich", 6, 5)
    addFood("farmersdelight:chicken_sandwich", 8, 7)
    addFood("farmersdelight:hamburger", 9, 8)
    addFood("farmersdelight:bacon_sandwich", 7, 6)
    addFood("farmersdelight:mutton_wrap", 8, 7)
    addFood("farmersdelight:dumplings", 6, 5)
    addFood("farmersdelight:stuffed_potato", 6, 5)
    addFood("farmersdelight:cabbage_rolls", 6, 5)
    addFood("farmersdelight:salmon_roll", 6, 5)
    addFood("farmersdelight:cod_roll", 5, 4)
    addFood("farmersdelight:kelp_roll", 5, 4)
    addFood("farmersdelight:kelp_roll_slice", 1, 0)
    addFood("farmersdelight:cooked_rice", 4, 3)
    addFood("farmersdelight:mixed_salad", 5, 4)
    addFood("farmersdelight:nether_salad", 5, 4)
    addFood("farmersdelight:fried_rice", 7, 6)
    addFood("farmersdelight:bacon_and_eggs", 8, 7)
    addFood("farmersdelight:pasta_with_meatballs", 10, 9)
    addFood("farmersdelight:pasta_with_mutton_chop", 10, 9)
    addFood("farmersdelight:roasted_mutton_chops", 8, 7)
    addFood("farmersdelight:steak_and_potatoes", 10, 9)
    addFood("farmersdelight:vegetable_noodles", 8, 7)
    addFood("farmersdelight:ratatouille", 8, 7)
    addFood("farmersdelight:squid_ink_pasta", 9, 8)
    addFood("farmersdelight:grilled_salmon", 8, 7)
    addFood("farmersdelight:mushroom_rice", 7, 6)
    addFood("farmersdelight:roast_chicken", 12, 11)
    addFood("farmersdelight:stuffed_pumpkin", 10, 9)
    addFood("farmersdelight:honey_glazed_ham", 12, 11)
    addFood("farmersdelight:shepherds_pie", 12, 11)
    addFood("farmersdelight:gleaming_salad", 10, 9)

    // Farmers Delight 汤类 / 炖菜
    addFood("farmersdelight:beef_stew", 10, 11)
    addFood("farmersdelight:chicken_soup", 10, 11)
    addFood("farmersdelight:vegetable_soup", 9, 10)
    addFood("farmersdelight:fish_stew", 10, 11)
    addFood("farmersdelight:pumpkin_soup", 9, 10)
    addFood("farmersdelight:baked_cod_stew", 10, 11)
    addFood("farmersdelight:noodle_soup", 10, 11)
    addFood("farmersdelight:onion_soup", 9, 10)
    addFood("farmersdelight:bone_broth", 7, 8)

    // Brewin' And Chewin' 饮品
    addDrink("brewinandchewin:beer", 10, 8)
    addDrink("brewinandchewin:vodka", 8, 4)
    addDrink("brewinandchewin:mead", 10, 8)
    addDrink("brewinandchewin:rice_wine", 10, 8)
    addDrink("brewinandchewin:egg_grog", 12, 12)
    addDrink("brewinandchewin:strongroot_ale", 10, 8)
    addDrink("brewinandchewin:saccharine_rum", 10, 6)
    addDrink("brewinandchewin:pale_jane", 10, 8)
    addDrink("brewinandchewin:salty_folly", 10, 6)
    addDrink("brewinandchewin:steel_toe_stout", 10, 6)  
    addDrink("brewinandchewin:glittering_grenadine", 12, 12)
    addDrink("brewinandchewin:bloody_mary", 12, 10)
    addDrink("brewinandchewin:red_rum", 10, 6)
    addDrink("brewinandchewin:withering_dross", 16, 18)
    addDrink("brewinandchewin:dread_nog", 14, 14)

    // // Brewin' And Chewin' 固体食物
    addFood("brewinandchewin:kimchi", 2, 1)
    addFood("brewinandchewin:jerky", 1, 0)
    addFood("brewinandchewin:pickled_pickles", 2, 2)
    addFood("brewinandchewin:kippers", 3, 2)
    addFood("brewinandchewin:cocoa_fudge", 3, 2)
    addFood("brewinandchewin:vegetable_omelet", 8, 8)
    addFood("brewinandchewin:cheesy_pasta", 10, 10)
    addFood("brewinandchewin:scarlet_pierogi", 8, 8)
    addFood("brewinandchewin:horror_lasagna", 10, 9)
    addFood("brewinandchewin:flaxen_cheese_wedge", 2, 1)
    addFood("brewinandchewin:scarlet_cheese_wedge", 2, 1)
    addFood("brewinandchewin:pizza_slice", 4, 3)
    addFood("brewinandchewin:ham_and_cheese_sandwich", 7, 6)
    addFood("brewinandchewin:quiche_slice", 3, 2)
    addFood("brewinandchewin:sweet_berry_jam", 3, 1)
    addFood("brewinandchewin:glow_berry_marmalade", 3, 2)
    addFood("brewinandchewin:apple_jelly", 3, 2)

    // Brewin' And Chewin' 汤类 / 奶酪火锅
    addFood("brewinandchewin:creamy_onion_soup", 9, 10)
    addFood("brewinandchewin:fiery_fondue", 10, 9)

    // Rustic Delight 饮品
    addDrink("rusticdelight:coffee", 10, 12)
    addDrink("rusticdelight:dark_coffee", 8, 10)
    addDrink("rusticdelight:honey_coffee", 10, 12)
    addDrink("rusticdelight:milk_coffee", 12, 14)
    addDrink("rusticdelight:chocolate_coffee", 12, 14)
    addDrink("rusticdelight:syrup_coffee", 10, 12)

    // Rustic Delight 固体食物
    addFood("rusticdelight:baked_potato_slices", 1, 0)
    addFood("rusticdelight:bell_pepper_green", 1, 0)
    addFood("rusticdelight:bell_pepper_red", 1, 0)
    addFood("rusticdelight:bell_pepper_yellow", 1, 0)
    addFood("rusticdelight:bell_pepper_roll_green", 5, 4)
    addFood("rusticdelight:bell_pepper_roll_red", 5, 4)
    addFood("rusticdelight:bell_pepper_roll_yellow", 5, 4)
    addFood("rusticdelight:bell_pepper_slice_green", 1, 0)
    addFood("rusticdelight:bell_pepper_slice_red", 1, 0)
    addFood("rusticdelight:bell_pepper_slice_yellow", 1, 0)
    addFood("rusticdelight:calamari", 1, 0)
    addFood("rusticdelight:calamari_roll", 5, 4)
    addFood("rusticdelight:calamari_slice", 1, 0)
    addFood("rusticdelight:cherry_blossom_cheesecake_slice", 3, 2)
    addFood("rusticdelight:cherry_blossom_cookie", 1, 0)
    addFood("rusticdelight:cherry_blossom_pancake", 4, 3)
    addFood("rusticdelight:cherry_blossom_roll", 4, 3)
    addFood("rusticdelight:chocolate_pancake", 5, 4)
    addFood("rusticdelight:coffee_braised_beef", 9, 8)
    addFood("rusticdelight:coffee_cookie", 1, 0)
    addFood("rusticdelight:cooked_calamari", 3, 2)
    addFood("rusticdelight:cooked_calamari_slice", 1, 0)
    addFood("rusticdelight:fried_calamari", 5, 4)
    addFood("rusticdelight:fried_chicken", 10, 9)
    addFood("rusticdelight:fried_dough", 3, 2)
    addFood("rusticdelight:fried_dumplings", 6, 5)
    addFood("rusticdelight:fried_mushrooms", 8, 6)
    addFood("rusticdelight:fruit_beignet", 4, 3)
    addFood("rusticdelight:honey_pancake", 5, 4)
    addFood("rusticdelight:pancake", 4, 3)
    addFood("rusticdelight:potato_salad", 5, 4)
    addFood("rusticdelight:pumpkin_pancake", 5, 4)
    addFood("rusticdelight:roasted_bell_pepper_green", 1, 0)
    addFood("rusticdelight:roasted_bell_pepper_red", 1, 0)
    addFood("rusticdelight:roasted_bell_pepper_yellow", 1, 0)
    addFood("rusticdelight:roasted_bell_pepper_slice_green", 1, 0)
    addFood("rusticdelight:roasted_bell_pepper_slice_red", 1, 0)
    addFood("rusticdelight:roasted_bell_pepper_slice_yellow", 1, 0)
    addFood("rusticdelight:spring_rolls", 6, 5)
    addFood("rusticdelight:stuffed_bell_pepper_green", 7, 6)
    addFood("rusticdelight:stuffed_bell_pepper_red", 7, 6)
    addFood("rusticdelight:stuffed_bell_pepper_yellow", 7, 6)
    addFood("rusticdelight:sweet_salad", 5, 4)
    addFood("rusticdelight:syrup_cheesecake_slice", 3, 2)
    addFood("rusticdelight:syrup_cookie", 1, 0)
    addFood("rusticdelight:syrup_sandwich", 5, 4)
    addFood("rusticdelight:vegetable_pancake", 5, 4)
    addFood("rusticdelight:bell_pepper_pasta", 8, 7)

    // Rustic Delight 汤类
    addFood("rusticdelight:bell_pepper_soup", 8, 9)

    // Vegan Delight 饮品
    addDrink("vegandelight:soymilk_bottle", 7, 8)

    // Vegan Delight 固体食物
    addFood("vegandelight:tofu", 2, 2)
    addFood("vegandelight:silken_tofu", 2, 2)
    addFood("vegandelight:minced_tofu", 1, 0)
    addFood("vegandelight:tofu_slices", 1, 0)
    addFood("vegandelight:tofish", 2, 1)
    addFood("vegandelight:tofish_roll", 5, 4)
    addFood("vegandelight:tofu_patty", 2, 1)
    addFood("vegandelight:smoked_tofu", 3, 2)
    addFood("vegandelight:smoked_tofish", 4, 3)
    addFood("vegandelight:smoked_tofish_roll", 6, 5)
    addFood("vegandelight:smoked_tofu_slices", 2, 1)
    addFood("vegandelight:cooked_tofu", 3, 2)
    addFood("vegandelight:cooked_tofu_slices", 2, 1)
    addFood("vegandelight:cooked_tofish", 4, 3)
    addFood("vegandelight:cooked_smoked_tofu", 4, 3)
    addFood("vegandelight:cooked_smoked_tofish", 5, 4)
    addFood("vegandelight:cooked_smoked_tofu_slices", 3, 2)
    addFood("vegandelight:soybean", 1, 0)
    addFood("vegandelight:applesauce", 2, 1)

    // Ratatouille 固体食物
    addFood("ratatouille:sausage", 5, 4)

    // Alex's Mobs 固体食物
    addFood("alexsmobs:banana", 2, 1)
    addFood("alexsmobs:lobster_tail", 2, 1)
    addFood("alexsmobs:cooked_lobster_tail", 4, 3)
    addFood("alexsmobs:sopa_de_macaco", 8, 9)
    addFood("alexsmobs:moose_ribs", 2, 1)
    addFood("alexsmobs:cooked_moose_ribs", 5, 4)
    addFood("alexsmobs:shrimp_fried_rice", 7, 6)
    addFood("alexsmobs:boiled_emu_egg", 3, 2)
    addFood("alexsmobs:kangaroo_meat", 2, 1)
    addFood("alexsmobs:cooked_kangaroo_meat", 5, 4)
    addFood("alexsmobs:kangaroo_burger", 8, 7)
    addFood("alexsmobs:cosmic_cod", 1, 0)
    addFood("alexsmobs:rainbow_jelly", 2, 1)
    addFood("alexsmobs:raw_catfish", 1, 0)
    addFood("alexsmobs:cooked_catfish", 4, 3)
    addFood("alexsmobs:flying_fish", 4, 3)
    addFood("alexsmobs:mosquito_repellent_stew", 4, 3)

    // Alex's Delight 固体食物
    addFood("alexsdelight:raw_bison", 2, 1)
    addFood("alexsdelight:raw_bunfungus", 1, 1)
    addFood("alexsdelight:kangaroo_shank", 2, 1)
    addFood("alexsdelight:loose_moose_rib", 2, 1)
    addFood("alexsdelight:bison_mince", 1, 0)
    addFood("alexsdelight:bison_patty", 2, 1)
    addFood("alexsdelight:raw_bunfungus_drumstick", 1, 0)
    addFood("alexsdelight:raw_catfish_slice", 1, 0)
    addFood("alexsdelight:cooked_bison", 5, 4)
    addFood("alexsdelight:cooked_bunfungus", 4, 3)
    addFood("alexsdelight:cooked_centipede_leg", 3, 2)
    addFood("alexsdelight:cooked_kangaroo_shank", 5, 4)
    addFood("alexsdelight:cooked_loose_moose_rib", 5, 4)
    addFood("alexsdelight:cooked_bunfungus_drumstick", 3, 2)
    addFood("alexsdelight:cooked_catfish_slice", 3, 2)
    addFood("alexsdelight:gongylidia_bruschetta", 4, 3)
    addFood("alexsdelight:maggot_salad", 4, 3)
    addFood("alexsdelight:bison_burger", 9, 8)
    addFood("alexsdelight:bunfungus_sandwich", 8, 7)
    addFood("alexsdelight:lobster_pasta", 9, 8)
    addFood("alexsdelight:kangaroo_pasta", 10, 9)

    // Alex's Delight 汤类 / 炖菜
    addFood("alexsdelight:kangaroo_stew", 9, 10)
    addFood("alexsdelight:acacia_blossom_soup", 9, 10)

    // Hybrid Aquatic 固体食物
    // 仅恢复 spawner.json 中仍允许生成的水生生物对应食物, 其余继续关闭
    // addFood("hybrid-aquatic:anglerfish", 1, 0)
    // addFood("hybrid-aquatic:barreleye", 1, 0)
    // addFood("hybrid-aquatic:blowfish", 1, 0)
    // addFood("hybrid-aquatic:blue_spotted_stingray", 1, 0)
    // addFood("hybrid-aquatic:boxfish", 1, 0)
    // addFood("hybrid-aquatic:carp", 1, 0)
    // addFood("hybrid-aquatic:clownfish", 1, 0)
    addFood("hybrid-aquatic:coelacanth", 1, 0)
    addFood("hybrid-aquatic:cooked_crab", 3, 2)
    // addFood("hybrid-aquatic:cooked_crayfish", 3, 2)
    addFood("hybrid-aquatic:cooked_fish_meat", 4, 3)
    addFood("hybrid-aquatic:cooked_fish_steak", 5, 4)
    // addFood("hybrid-aquatic:cooked_lobster", 4, 3)
    // addFood("hybrid-aquatic:cooked_lobster_tail", 4, 3)
    // addFood("hybrid-aquatic:cooked_shrimp", 3, 2)
    // addFood("hybrid-aquatic:cooked_tentacle", 3, 2)
    // addFood("hybrid-aquatic:damselfish", 1, 0)
    // addFood("hybrid-aquatic:danio", 1, 0)
    // addFood("hybrid-aquatic:dragonfish", 1, 0)
    addFood("hybrid-aquatic:flashlight_fish", 1, 0)
    // addFood("hybrid-aquatic:flying_fish", 1, 0)
    addFood("hybrid-aquatic:golden_dorado", 1, 0)
    addFood("hybrid-aquatic:goldfish", 1, 0)
    // addFood("hybrid-aquatic:gourami", 1, 0)
    addFood("hybrid-aquatic:herring", 1, 0)
    // addFood("hybrid-aquatic:john_dory", 1, 0)
    addFood("hybrid-aquatic:lionfish", 1, 0)
    addFood("hybrid-aquatic:mackerel", 1, 0)
    addFood("hybrid-aquatic:mahi", 1, 0)
    // addFood("hybrid-aquatic:moray_eel", 1, 0)
    addFood("hybrid-aquatic:needlefish", 1, 0)
    addFood("hybrid-aquatic:opah", 1, 0)
    // addFood("hybrid-aquatic:oscar", 1, 0)
    // addFood("hybrid-aquatic:parrotfish", 1, 0)
    // addFood("hybrid-aquatic:pearlfish", 1, 0)
    addFood("hybrid-aquatic:piranha", 1, 0)
    // addFood("hybrid-aquatic:ratfish", 1, 0)
    addFood("hybrid-aquatic:raw_crab", 1, 0)
    // addFood("hybrid-aquatic:raw_crayfish", 1, 0)
    addFood("hybrid-aquatic:raw_fish_meat", 1, 0)
    addFood("hybrid-aquatic:raw_fish_steak", 2, 1)
    // addFood("hybrid-aquatic:raw_lobster", 1, 0)
    // addFood("hybrid-aquatic:raw_lobster_tail", 1, 0)
    // addFood("hybrid-aquatic:raw_shrimp", 1, 0)
    // addFood("hybrid-aquatic:raw_tentacle", 1, 0)
    // addFood("hybrid-aquatic:rockfish", 1, 0)
    // addFood("hybrid-aquatic:sea_bass", 1, 0)
    // addFood("hybrid-aquatic:sheepshead_wrasse", 1, 0)
    // addFood("hybrid-aquatic:stonefish", 1, 0)
    addFood("hybrid-aquatic:ocean_sunfish", 1, 0)
    // addFood("hybrid-aquatic:surgeonfish", 1, 0)
    // addFood("hybrid-aquatic:tiger_barb", 1, 0)
    addFood("hybrid-aquatic:triggerfish", 1, 0)
    addFood("hybrid-aquatic:tuna", 1, 0)
    // addFood("hybrid-aquatic:uni", 2, 1)

    // Corn Delight 饮品
    addDrink("corn_delight:creamy_corn_drink", 8, 9)

    // Corn Delight 固体食物
    addFood("corn_delight:corn", 1, 0)
    addFood("corn_delight:grilled_corn", 2, 1)
    addFood("corn_delight:boiled_corn", 3, 3)
    addFood("corn_delight:popcorn", 0, 0)
    addFood("corn_delight:caramel_popcorn", 1, 0)
    addFood("corn_delight:creamed_corn", 4, 4)
    addFood("corn_delight:cornbread", 2, 1)
    addFood("corn_delight:tortilla", 1, 0)
    addFood("corn_delight:tortilla_chip", 0, 0)
    addFood("corn_delight:cornbread_batter", 3, 2)
    addFood("corn_delight:tortilla_raw", 1, 0)
    addFood("corn_delight:corn_dog", 5, 4)
    addFood("corn_delight:classic_corn_dog", 5, 4)
    addFood("corn_delight:taco", 6, 5)
    addFood("corn_delight:cornbread_stuffing", 5, 4)
    addFood("corn_delight:nachos_bowl", 7, 6)

    // Corn Delight 汤类
    addFood("corn_delight:corn_soup", 9, 10)

    // // Spore 固体食物
    addFood("spore:slice_of_heartpie", 4, 3)
    addFood("spore:biomass_bacon", 2, 1)
    addFood("spore:meaty_icecream", 4, 4)
    addFood("spore:tendon_gum", 2, 1)
    addFood("spore:fleshy_ribs", 2, 1)
    addFood("spore:decayed_limbs", 8, 7)
    addFood("spore:sausage", 6, 6)
    addFood("spore:heart_kebab", 1, 1)
    addFood("spore:roasted_heart_kebab", 7, 8)
    addFood("spore:amalgamated_roast", 10, 10)
    addFood("spore:eldritch_sushi", 8, 8)
    addFood("spore:stuffed_abomination", 10, 9)
    addFood("spore:roasted_tumor", 6, 8)
    addFood("spore:brain_noodles", 8, 7)
    addFood("spore:fried_wing_membrane", 4, 3)
    addFood("spore:fungal_burger", 10, 8)
    addFood("spore:milky_sack", 4, 3)

    // Spore 汤类 / 酱类
    addFood("spore:skull_soup", 8, 9)
    addFood("spore:organoid_soup", 8, 9)
    addFood("spore:fungal_sauce", 6, 6)
    addFood("spore:fiber_stew", 5, 10)
    addFood("spore:vigil_eye_soup", 10, 10)

    // 明显偏干或不适合作为正常补水来源的食物暂时不加入:
    // bread, cookie, dried_kelp, baked_potato, pumpkin_pie
    // 以及带明显负面效果的 rotten_flesh, spider_eye, poisonous_potato, pufferfish
})
