//紫水晶
const amethyst_block = ['minecraft:amethyst_block','chipped:amethyst_block_bricks','chipped:amethyst_block_mini_tiles','chipped:amethyst_block_pillar','chipped:amethyst_block_pillar_top','chipped:amethyst_block_scales','chipped:angry_amethyst_block','chipped:blank_amethyst_block_carving','chipped:bordered_amethyst_block','chipped:brick_bordered_amethyst_block','chipped:carved_amethyst_block','chipped:checkered_amethyst_block_tiles','chipped:cobbled_amethyst_block','chipped:cracked_amethyst_block_bricks','chipped:cracked_disordered_amethyst_block_bricks','chipped:cracked_flat_amethyst_block_tiles','chipped:creeper_amethyst_block_carving','chipped:crying_amethyst_block','chipped:curly_amethyst_block_pillar','chipped:cut_amethyst_block_column','chipped:cut_blank_amethyst_block','chipped:duh_amethyst_block','chipped:edged_amethyst_block_bricks','chipped:engraved_amethyst_block','chipped:eroded_amethyst_block','chipped:etched_amethyst_block_bricks','chipped:fine_amethyst_block_pillar','chipped:flat_amethyst_block_tiles','chipped:glad_amethyst_block','chipped:inlayed_amethyst_block','chipped:inscribed_amethyst_block','chipped:layed_amethyst_block_bricks','chipped:loded_amethyst_block','chipped:massive_amethyst_block_bricks','chipped:offset_amethyst_block_bricks','chipped:ornate_amethyst_block_pillar','chipped:overlapping_amethyst_block_tiles','chipped:pillar_amethyst_block_bricks','chipped:polished_amethyst_block','chipped:prismal_amethyst_block_remnants','chipped:rough_amethyst_block','chipped:rounded_amethyst_block_bricks','chipped:runic_carved_amethyst_block','chipped:sad_amethyst_block','chipped:sanded_amethyst_block','chipped:simple_amethyst_block_pillar','chipped:small_amethyst_block_bricks','chipped:smoothed_double_inlayed_amethyst_block','chipped:smooth_amethyst_block_column','chipped:smooth_inlayed_amethyst_block','chipped:smooth_ringed_amethyst_block','chipped:spider_amethyst_block_carving','chipped:spiraled_amethyst_block','chipped:stacked_amethyst_block_bricks','chipped:thick_inlayed_amethyst_block','chipped:tiled_amethyst_block','chipped:tiled_amethyst_block_column','chipped:tiled_bordered_amethyst_block','chipped:tiny_amethyst_block_bricks','chipped:tiny_brick_bordered_amethyst_block','chipped:tiny_layered_amethyst_block_bricks','chipped:tiny_layered_amethyst_block_slabs','chipped:trodden_amethyst_block','chipped:unamused_amethyst_block','chipped:vertical_cut_amethyst_block','chipped:vertical_disordered_amethyst_block_bricks','chipped:weathered_amethyst_block'] 
//煤块
const coal_block = ['minecraft:coal_block','chipped:angry_coal_block','chipped:blank_coal_block_carving','chipped:bordered_coal_block','chipped:brick_bordered_coal_block','chipped:carved_coal_block','chipped:checkered_coal_block_tiles','chipped:coal_block_bricks','chipped:coal_block_mini_tiles','chipped:coal_block_pillar','chipped:coal_block_pillar_top','chipped:coal_block_scales','chipped:cobbled_coal_block','chipped:cracked_coal_block_bricks','chipped:cracked_disordered_coal_block_bricks','chipped:cracked_flat_coal_block_tiles','chipped:creeper_coal_block_carving','chipped:crying_coal_block','chipped:curly_coal_block_pillar','chipped:cut_blank_coal_block','chipped:cut_coal_block_column','chipped:duh_coal_block','chipped:edged_coal_block_bricks','chipped:engraved_coal_block','chipped:eroded_coal_block','chipped:etched_coal_block_bricks','chipped:filelist','chipped:fine_coal_block_pillar','chipped:flat_coal_block_tiles','chipped:glad_coal_block','chipped:inlayed_coal_block','chipped:inscribed_coal_block','chipped:layed_coal_block_bricks','chipped:loded_coal_block','chipped:massive_coal_block_bricks','chipped:offset_coal_block_bricks','chipped:ornate_coal_block_pillar','chipped:overlapping_coal_block_tiles','chipped:pillar_coal_block_bricks','chipped:polished_coal_block','chipped:prismal_coal_block_remnants','chipped:rough_coal_block','chipped:rounded_coal_block_bricks','chipped:runic_carved_coal_block','chipped:sad_coal_block','chipped:sanded_coal_block','chipped:simple_coal_block_pillar','chipped:small_coal_block_bricks','chipped:smoothed_double_inlayed_coal_block','chipped:smooth_coal_block_column','chipped:smooth_inlayed_coal_block','chipped:smooth_ringed_coal_block','chipped:spider_coal_block_carving','chipped:spiraled_coal_block','chipped:stacked_coal_block_bricks','chipped:thick_inlayed_coal_block','chipped:tiled_bordered_coal_block','chipped:tiled_coal_block','chipped:tiled_coal_block_column','chipped:tiny_brick_bordered_coal_block','chipped:tiny_coal_block_bricks','chipped:tiny_layered_coal_block_bricks','chipped:tiny_layered_coal_block_slabs','chipped:trodden_coal_block','chipped:unamused_coal_block','chipped:vertical_cut_coal_block','chipped:vertical_disordered_coal_block_bricks','chipped:weathered_coal_block'] 
//哭泣黑曜石
const crying_obsidian = ['minecraft:crying_obsidian','chipped:angry_crying_obsidian','chipped:blank_crying_obsidian_carving','chipped:bordered_crying_obsidian','chipped:brick_bordered_crying_obsidian','chipped:carved_crying_obsidian','chipped:checkered_crying_obsidian_tiles','chipped:cobbled_crying_obsidian','chipped:cracked_crying_obsidian_bricks','chipped:cracked_disordered_crying_obsidian_bricks','chipped:cracked_flat_crying_obsidian_tiles','chipped:creeper_crying_obsidian_carving','chipped:crying_crying_obsidian','chipped:crying_obsidian_bricks','chipped:crying_obsidian_mini_tiles','chipped:crying_obsidian_pillar','chipped:crying_obsidian_pillar_top','chipped:crying_obsidian_scales','chipped:curly_crying_obsidian_pillar','chipped:cut_blank_crying_obsidian','chipped:cut_crying_obsidian_column','chipped:duh_crying_obsidian','chipped:edged_crying_obsidian_bricks','chipped:engraved_crying_obsidian','chipped:eroded_crying_obsidian','chipped:etched_crying_obsidian_bricks','chipped:filelist','chipped:fine_crying_obsidian_pillar','chipped:flat_crying_obsidian_tiles','chipped:glad_crying_obsidian','chipped:inlayed_crying_obsidian','chipped:inscribed_crying_obsidian','chipped:layed_crying_obsidian_bricks','chipped:loded_crying_obsidian','chipped:massive_crying_obsidian_bricks','chipped:offset_crying_obsidian_bricks','chipped:ornate_crying_obsidian_pillar','chipped:overlapping_crying_obsidian_tiles','chipped:pillar_crying_obsidian_bricks','chipped:polished_crying_obsidian','chipped:prismal_crying_obsidian_remnants','chipped:rough_crying_obsidian','chipped:rounded_crying_obsidian_bricks','chipped:runic_carved_crying_obsidian','chipped:sad_crying_obsidian','chipped:sanded_crying_obsidian','chipped:simple_crying_obsidian_pillar','chipped:small_crying_obsidian_bricks','chipped:smoothed_double_inlayed_crying_obsidian','chipped:smooth_crying_obsidian_column','chipped:smooth_inlayed_crying_obsidian','chipped:smooth_ringed_crying_obsidian','chipped:spider_crying_obsidian_carving','chipped:spiraled_crying_obsidian','chipped:stacked_crying_obsidian_bricks','chipped:thick_inlayed_crying_obsidian','chipped:tiled_bordered_crying_obsidian','chipped:tiled_crying_obsidian','chipped:tiled_crying_obsidian_column','chipped:tiny_brick_bordered_crying_obsidian','chipped:tiny_crying_obsidian_bricks','chipped:tiny_layered_crying_obsidian_bricks','chipped:tiny_layered_crying_obsidian_slabs','chipped:trodden_crying_obsidian','chipped:unamused_crying_obsidian','chipped:vertical_cut_crying_obsidian','chipped:vertical_disordered_crying_obsidian_bricks','chipped:weathered_crying_obsidian'] 
//磁石
const lodestone = ['minecraft:lodestone','chipped:angry_lodestone','chipped:blank_lodestone_carving','chipped:blank_lodestone_side','chipped:bordered_lodestone','chipped:brick_bordered_lodestone','chipped:carved_lodestone','chipped:checkered_lodestone_tiles','chipped:cobbled_lodestone','chipped:cracked_disordered_lodestone_bricks','chipped:cracked_flat_lodestone_tiles','chipped:cracked_lodestone_bricks','chipped:creeper_lodestone_carving','chipped:crying_lodestone','chipped:curly_lodestone_pillar','chipped:cut_blank_lodestone','chipped:cut_lodestone_column','chipped:diamond_lodestone','chipped:dot_lodestone','chipped:duh_lodestone','chipped:edged_lodestone_bricks','chipped:engraved_lodestone','chipped:eroded_lodestone','chipped:etched_lodestone_bricks','chipped:filelist','chipped:fine_lodestone_pillar','chipped:flat_lodestone_tiles','chipped:glad_lodestone','chipped:inlayed_lodestone','chipped:inscribed_lodestone','chipped:layed_lodestone_bricks','chipped:lodestone_bricks','chipped:lodestone_mini_tiles','chipped:lodestone_pillar','chipped:lodestone_pillar_top','chipped:lodestone_scales','chipped:massive_lodestone_bricks','chipped:offset_lodestone_bricks','chipped:ornate_lodestone_pillar','chipped:overlapping_lodestone_tiles','chipped:pillar_lodestone_bricks','chipped:polished_lodestone','chipped:prismal_lodestone_remnants','chipped:ring_lodestone','chipped:ring_lodestone_side','chipped:rough_lodestone','chipped:rounded_lodestone_bricks','chipped:runic_carved_lodestone','chipped:sad_lodestone','chipped:sanded_lodestone','chipped:sea_lantern_lodestone','chipped:simple_lodestone_pillar','chipped:small_lodestone_bricks','chipped:smoothed_double_inlayed_lodestone','chipped:smooth_lodestone_column','chipped:smooth_ringed_lodestone','chipped:spider_lodestone_carving','chipped:spiraled_lodestone','chipped:stacked_lodestone_bricks','chipped:thick_inlayed_lodestone','chipped:tiled_bordered_lodestone','chipped:tiled_lodestone','chipped:tiled_lodestone_column','chipped:tiny_brick_bordered_lodestone','chipped:tiny_layered_lodestone_bricks','chipped:tiny_layered_lodestone_slabs','chipped:tiny_lodestone_bricks','chipped:trodden_lodestone','chipped:unamused_lodestone','chipped:vertical_cut_lodestone','chipped:vertical_disordered_lodestone_bricks','chipped:watching_lodestone','chipped:weathered_lodestone','chipped:wider_diamond_lodestone','chipped:wider_ring_lodestone','chipped:wider_watching_lodestone'] 
//青金石块
const lapis_block = ['minecraft:lapis_block','chipped:angry_lapis_block','chipped:blank_lapis_block_carving','chipped:bordered_lapis_block','chipped:brick_bordered_lapis_block','chipped:carved_lapis_block','chipped:checkered_lapis_block_tiles','chipped:cobbled_lapis_block','chipped:cracked_disordered_lapis_block_bricks','chipped:cracked_flat_lapis_block_tiles','chipped:cracked_lapis_block_bricks','chipped:creeper_lapis_block_carving','chipped:crying_lapis_block','chipped:curly_lapis_block_pillar','chipped:cut_blank_lapis_block','chipped:cut_lapis_block_column','chipped:duh_lapis_block','chipped:edged_lapis_block_bricks','chipped:engraved_lapis_block','chipped:eroded_lapis_block','chipped:etched_lapis_block_bricks','chipped:filelist','chipped:fine_lapis_block_pillar','chipped:flat_lapis_block_tiles','chipped:glad_lapis_block','chipped:inlayed_lapis_block','chipped:inscribed_lapis_block','chipped:lapis_block_bricks','chipped:lapis_block_mini_tiles','chipped:lapis_block_pillar','chipped:lapis_block_pillar_top','chipped:lapis_block_scales','chipped:layed_lapis_block_bricks','chipped:loded_lapis_block','chipped:massive_lapis_block_bricks','chipped:offset_lapis_block_bricks','chipped:ornate_lapis_block_pillar','chipped:overlapping_lapis_block_tiles','chipped:pillar_lapis_block_bricks','chipped:polished_lapis_block','chipped:prismal_lapis_block_remnants','chipped:rough_lapis_block','chipped:rounded_lapis_block_bricks','chipped:runic_carved_lapis_block','chipped:sad_lapis_block','chipped:sanded_lapis_block','chipped:simple_lapis_block_pillar','chipped:small_lapis_block_bricks','chipped:smoothed_double_inlayed_lapis_block','chipped:smooth_inlayed_lapis_block','chipped:smooth_lapis_block_column','chipped:smooth_ringed_lapis_block','chipped:spider_lapis_block_carving','chipped:spiraled_lapis_block','chipped:stacked_lapis_block_bricks','chipped:thick_inlayed_lapis_block','chipped:tiled_bordered_lapis_block','chipped:tiled_lapis_block','chipped:tiled_lapis_block_column','chipped:tiny_brick_bordered_lapis_block','chipped:tiny_lapis_block_bricks','chipped:tiny_layered_lapis_block_bricks','chipped:tiny_layered_lapis_block_slabs','chipped:trodden_lapis_block','chipped:unamused_lapis_block','chipped:vertical_cut_lapis_block','chipped:vertical_disordered_lapis_block_bricks','chipped:weathered_lapis_block'] 
//钻石块
const diamond_block = ['minecraft:diamond_block','chipped:ancient_diamond_block','chipped:chipped_diamond_block','chipped:diamond_block_panels','chipped:embossed_diamond_block','chipped:engraved_diamond_block','chipped:filelist','chipped:layered_diamond_block','chipped:plated_diamond_block','chipped:pressed_diamond_block','chipped:reinforced_diamond_block','chipped:sheet_diamond_block','chipped:shuttered_diamond_block','chipped:stacked_diamond_block'] 

//绿宝石块
const emerald_block = ['minecraft:emerald_block','chipped:ancient_emerald_block','chipped:chipped_emerald_block','chipped:embossed_emerald_block','chipped:emerald_block_panels','chipped:engraved_emerald_block','chipped:filelist','chipped:layered_emerald_block','chipped:plated_emerald_block','chipped:polished_emerald_block','chipped:reinforced_emerald_block','chipped:sheet_emerald_block','chipped:shuttered_emerald_block','chipped:stacked_emerald_block'] 

//金块
const gold_block = ['minecraft:gold_block','chipped:ancient_gold_block','chipped:chipped_gold_block','chipped:embossed_gold_block','chipped:engraved_gold_block','chipped:filelist','chipped:gold_block_panels','chipped:layered_gold_block','chipped:plated_gold_block','chipped:pressed_gold_block','chipped:reinforced_gold_block','chipped:sheet_gold_block','chipped:shuttered_gold_block','chipped:stacked_gold_block'] 

//铁块
const iron_block =  ['minecraft:iron_block','chipped:ancient_iron_block','chipped:chipped_iron_block','chipped:engraved_iron_block','chipped:filelist','chipped:iron_block_panels','chipped:layered_iron_block','chipped:plated_iron_block','chipped:polished_iron_block','chipped:pressed_iron_block','chipped:reinforced_iron_block','chipped:sheet_iron_block','chipped:shuttered_iron_block','chipped:stacked_iron_block'] 

//下界合金
const netherite_block = ['minecraft:netherite_block','chipped:chipped_netherite_block','chipped:embossed_netherite_block','chipped:engraved_netherite_block','chipped:filelist','chipped:layered_netherite_block','chipped:netherite_block_panels','chipped:plated_netherite_block','chipped:polished_netherite_block','chipped:pressed_netherite_block','chipped:reinforced_netherite_block','chipped:sheet_netherite_block','chipped:shuttered_netherite_block','chipped:stacked_netherite_block'] 

//海绵
const sponge = ['minecraft:sponge','chipped:bulby_sponge','chipped:filelist','chipped:fine_sponge','chipped:giant_sponge','chipped:lush_sponge','chipped:old_sponge','chipped:smooth_sponge','chipped:soft_sponge'] 

//荧石
const glowstone = ['minecraft:glowstone','chipped:broken_glowstone','chipped:bulbed_glowstone','chipped:cracked_glowstone','chipped:double_inlayed_glowstone','chipped:edged_glowstone_lantern','chipped:fancy_glowstone_lantern','chipped:filelist','chipped:framed_glowstone_lantern','chipped:glowing_lodestone_side','chipped:glowstone_lantern','chipped:hived_glowstone','chipped:inlayed_glowstone','chipped:nether_engraved_glowstone','chipped:ornate_glowstone_lantern','chipped:patterned_glowstone','chipped:polished_glowstone','chipped:shimmering_glowstone','chipped:smooth_glowstone','chipped:thick_inlayed_glowstone','chipped:tiled_glowstone_pillar','chipped:wither_engraved_glowstone'] 

//涂蜡的铜块
const waxed_copper_block = ['minecraft:waxed_copper_block','chipped:ancient_waxed_copper_block','chipped:chipped_waxed_copper_block','chipped:embossed_waxed_copper_block','chipped:engraved_waxed_copper_block','chipped:filelist','chipped:layered_waxed_copper_block','chipped:plated_waxed_copper_block','chipped:pressed_waxed_copper_block','chipped:reinforced_waxed_copper_block','chipped:sheet_waxed_copper_block','chipped:shuttered_waxed_copper_block','chipped:stacked_waxed_copper_block'] 

//涂蜡的斑驳铜块
const waxed_exposed_copper_block = ['minecraft:waxed_exposed_copper','chipped:ancient_waxed_exposed_copper','chipped:chipped_waxed_exposed_copper','chipped:embossed_waxed_exposed_copper','chipped:engraved_waxed_exposed_copper','chipped:filelist','chipped:layered_waxed_exposed_copper','chipped:plated_waxed_exposed_copper','chipped:pressed_waxed_exposed_copper','chipped:reinforced_waxed_exposed_copper','chipped:sheet_waxed_exposed_copper','chipped:shuttered_waxed_exposed_copper','chipped:stacked_waxed_exposed_copper'] 

//涂蜡的锈蚀铜块
const waxed_weathered_copper = ['minecraft:waxed_weathered_copper','chipped:ancient_waxed_weathered_copper','chipped:chipped_waxed_weathered_copper','chipped:embossed_waxed_weathered_copper','chipped:engraved_waxed_weathered_copper','chipped:filelist','chipped:layered_waxed_weathered_copper','chipped:plated_waxed_weathered_copper','chipped:pressed_waxed_weathered_copper','chipped:reinforced_waxed_weathered_copper','chipped:sheet_waxed_weathered_copper','chipped:shuttered_waxed_weathered_copper','chipped:stacked_waxed_weathered_copper'] 

//涂蜡的氧化铜块
const waxed_oxidized_copper = ['minecraft:waxed_oxidized_copper','chipped:ancient_waxed_oxidized_copper','chipped:chipped_waxed_oxidized_copper','chipped:embossed_waxed_oxidized_copper','chipped:engraved_waxed_oxidized_copper','chipped:filelist','chipped:layered_waxed_oxidized_copper','chipped:plated_waxed_oxidized_copper','chipped:pressed_waxed_oxidized_copper','chipped:reinforced_waxed_oxidized_copper','chipped:sheet_waxed_oxidized_copper','chipped:shuttered_waxed_oxidized_copper','chipped:stacked_waxed_oxidized_copper'] 

ServerEvents.recipes(event=>{
    const create = event.recipes.create
    const vintage = event.recipes.vintageimprovements 

function addRecipes(arr,input)
{
    for(let i=0;i<arr.length;i++){
        if(arr[i] !== 'chipped:filelist')
        event.stonecutting(arr[i],input)
    }
}
//紫水晶
addRecipes(amethyst_block,'#chipped:amethyst_block')
//煤块
addRecipes(coal_block,'#chipped:coal_block')
//哭泣黑曜石
addRecipes(crying_obsidian,'#chipped:crying_obsidian')
//磁石
addRecipes(lodestone,'#chipped:lodestone')
//青金石块
addRecipes(lapis_block,'#chipped:lapis_block')
//钻石块
addRecipes(diamond_block,'#chipped:diamond_block')
//绿宝石块
addRecipes(emerald_block,'#chipped:emerald_block')
//金块
addRecipes(gold_block,'#chipped:gold_block')
//铁块
addRecipes(iron_block,'#chipped:iron_block')
//下界合金
addRecipes(netherite_block,'#chipped:netherite_block')
//海绵
addRecipes(sponge,'#chipped:sponge')
//荧石
addRecipes(glowstone,'#chipped:glowstone')
//涂蜡的铜块
addRecipes(waxed_copper_block,'#chipped:waxed_copper_block')
//涂蜡的斑驳铜块
addRecipes(waxed_exposed_copper_block,'#chipped:waxed_exposed_copper_block')
//涂蜡的锈蚀铜块
addRecipes(waxed_weathered_copper,'#chipped:waxed_weathered_copper')
//涂蜡的氧化铜块
addRecipes(waxed_oxidized_copper,'#chipped:waxed_oxidized_copper')

event.remove({id:'chipped:benches/alchemy_bench'})
event.remove({type:"chipped:alchemy_bench"})
})
